import Foundation
import XCTest

@testable import FacetKernel

/// Does a solve of a large pattern still complete, still close, and not fall off a cliff.
///
/// `Kiev Triangle` — 139 facets, 3-fold mirror, RI 2.160 — is the real design this stands in for. No
/// pattern file for it is authored, and none is authored here: its meets sit outside what this format
/// expresses, so a transcription would be a guess dressed as ground truth. What is left of that check is
/// scaling, and a generated pattern tests scaling exactly as well. Nothing below is ground truth for any
/// stone; the only claims are that 139 planes solve, close, and do so quickly.
final class ScaleTests: XCTestCase {
  func testAHundredAndThirtyNinePlanesSolveAndClose() throws {
    let pattern = Self.stepCut
    let solution = try solve(pattern, girdleTargetFraction: 0.04)

    XCTAssertEqual(solution.planes.count, 139)
    XCTAssertEqual(solution.tiers.count, pattern.tiers.count)
    XCTAssertNil(openEdge(of: solution.polytope), "the solid closes")
    XCTAssertGreaterThan(solution.polytope.vertices.count, 100)
  }

  /// A tripwire, not a target. The solve is cubic in planes where it builds the solid, so a change that
  /// made it quartic would still pass every correctness check in this package and only show up here.
  func testOneFullSolveStaysUnderFiveSeconds() throws {
    let started = ProcessInfo.processInfo.systemUptime
    _ = try solve(Self.stepCut, girdleTargetFraction: 0.04)
    let elapsed = ProcessInfo.processInfo.systemUptime - started

    print("139-plane solve: \(String(format: "%.3f", elapsed))s")
    XCTAssertLessThan(elapsed, 5.0, "one full solve of 139 planes")
  }

  // MARK: - The generated pattern

  /// A step cut on a 96 wheel: a girdle, three pavilion steps, three crown steps and a table, whose index
  /// counts add to 139 planes.
  ///
  /// Every step is cut to a point on the ridge its two predecessors share, interpolated toward the axis —
  /// the same shape of meet `Novice Ash-er` uses, which is what makes each named triple a real corner of
  /// the stone at the tier that names it. Each ring therefore sits inside the last by construction.
  private static let stepCut: FacetKernel.Pattern = {
    let every4 = Array(stride(from: 0, to: 96, by: 4))  // 24
    let every8 = Array(stride(from: 0, to: 96, by: 8))  // 12
    let every16 = Array(stride(from: 0, to: 96, by: 16))  // 6

    /// A point along the ridge where `outer` and `inner` meet, `percent` of the way to the axis.
    func inward(from outer: String, to inner: String, percent: Double) -> Meet {
      .fraction(
        from: .vertex(facets: [
          FacetRef(tier: outer, index: 0),
          FacetRef(tier: outer, index: 4),
          FacetRef(tier: inner, index: 0),
        ]),
        percent: percent,
        to: .tcp
      )
    }

    return FacetKernel.Pattern(
      formatVersion: 1,
      name: "generated 139-plane step cut",
      state: .inProgress,
      wheel: 96,
      ri: 1.54,
      designer: "",
      notes: "Generated by ScaleTests. Stands in for Kiev Triangle's plane count, nothing more.",
      tiers: [
        TierSpec(tier: "G", part: .gdl, angle: 90, indices: every4, meet: .size),
        TierSpec(tier: "P1", part: .pav, angle: 50, indices: every4, meet: .tcp),
        TierSpec(
          tier: "P2", part: .pav, angle: 46, indices: every4,
          meet: inward(from: "G", to: "P1", percent: 30)),
        TierSpec(
          tier: "P3", part: .pav, angle: 42, indices: every4,
          meet: inward(from: "P1", to: "P2", percent: 30)),
        TierSpec(tier: "C1", part: .crown, angle: 40, indices: every4, meet: .girdle),
        TierSpec(
          tier: "C2", part: .crown, angle: 30, indices: every8,
          meet: inward(from: "G", to: "C1", percent: 30)),
        TierSpec(
          tier: "C3", part: .crown, angle: 22, indices: every16,
          meet: inward(from: "C1", to: "C2", percent: 30)),
        TierSpec(
          tier: "T", part: .table, angle: 0, indices: [0],
          meet: inward(from: "C1", to: "C2", percent: 70)),
      ]
    )
  }()

  // MARK: - Closure

  /// The first facet edge no second facet shares, or `nil` when the surface is closed.
  ///
  /// This mirrors the rule validation applies, rather than calling `validate`: validation's other half
  /// rebuilds the solid once per tier to check named points, which is cubic in planes *per tier* and would
  /// dominate the timing this file exists to measure.
  private func openEdge(of polytope: Polytope) -> [Int]? {
    var shared: [[Int]: Int] = [:]
    var distinct: Set<[Int]> = []
    for polygon in polytope.facets.values where distinct.insert(polygon.sorted()).inserted {
      for edge in edges(of: polygon) { shared[edge, default: 0] += 1 }
    }
    return shared.first { $0.value != 2 }?.key
  }

  private func edges(of polygon: [Int]) -> [[Int]] {
    polygon.indices.map { [polygon[$0], polygon[($0 + 1) % polygon.count]].sorted() }
  }
}
